import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import 'bootstrap/dist/css/bootstrap.min.css';
import Link from 'next/link'
import { useEffect, useState } from "react"
import Card from 'react-bootstrap/Card';


export default function Home({ data }) {
 const [authors, setAuthors] = useState(data)
 console.log(authors)
  return (
    <div className='bg-dark'>

    
    <div className={styles.container}>
      <Head>
        <title>Aren</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>


<nav className="navbar navbar-expand-lg navbar-light bg-primary ">
        <div className="container-fluid ">
            <a className="navbar-brand text-light mx-5" href="/">BLOG.Me</a>
         
            <button className="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span className="navbar-toggler-icon"></span>
            </button>
            <div className="collapse navbar-collapse" id="navbarNav">
            <ul className="navbar-nav">
                <li className="nav-item">

                <Link href="/">
                    <a className="nav-link  mx-3">Home</a>
                </Link>
                
                </li>
                <li className="nav-item">
                <Link href="/post">
                    <a className="nav-link mx-3" >Post</a>
                </Link>
                </li>
                <li className="nav-item">
                <Link href="/author">
                    <a className="nav-link mx-3 active" >Author</a>
                </Link>
                </li>
            
            </ul>
            </div>
        </div>
        </nav>
</div>

      <main className={styles.main}>
        <div className={styles.grid}>
            {authors.map(author => (
                console.log(author),
                 <Card className="m-4 text-center bg-light text-dark" key={author.id} style={{ width: '20rem'}}>
                 {/* <Card.Img variant="top" src="holder.js/100px180" /> */}
                 <Card.Img variant="top" src={author.avatar_urls[96]} />
                 <Card.Body>
                     <Card.Title>{author.name}</Card.Title>
                     {/* <Card.Text>
                     {post.excerpt.rendered}
                     </Card.Text>
                     <Button variant="primary">Go somewhere</Button> */}
                 </Card.Body>
                 {/* <Card.Footer className="text-muted">{post.modified}</Card.Footer> */}
                 </Card>
            ))}
        </div>
      </main>
    </div>
    </div>
  )
}

export async function getServerSideProps() {
    // Fetch data from external API
    const res = await fetch(`https://fswd-wp.devnss.com/wp-json/wp/v2/users`)
    const data = await res.json()
  
    // Pass data to the page via props
    return { props: { data } }
  }
  

