import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import 'bootstrap/dist/css/bootstrap.min.css';
import Link from 'next/link'
import {Card, Button, InputGroup ,FormControl  }from 'react-bootstrap';
   
import React, { useEffect, useState } from "react"
import Parser from 'html-react-parser'



export default function Detail({id, posts}) {
    // const showposts = props.posts

    // const [post, setPost] = useState(posts)
    const [content, setContent] = useState()
    const [commented, setCommented] = useState([])

    React.useEffect(() => {
        async function fetchMyAPI() {
            let response = await fetch('https://fswd-wp.devnss.com/wp-json/wp/v2/comments?post=' + id)
            response = await response.json()
            setCommented(response)
        }

        fetchMyAPI()
    }, [commented])

    const checkpost = async () =>{
        const response = await fetch('https://fswd-wp.devnss.com/wp-json/wp/v2/comments',{
            method:'POST',
            body: JSON.stringify({post:id , content:content}),
            headers:{
                'Content-Type': 'application/json',
                Authorization: 'Basic ZnN3ZDpmc3dkLWNtcw==',
            }
        })
        const data = await response.json()
        console.log(data)
        setCommented(commented)

    }
    const handleChange =(event) => {
        setContent( event.target.value);
    }

  return (
    // console.log(showposts),
    // console.log(showposts.id),
    <div className={styles.container}>
        {/* {console.log(comments)} */}
      <Head>
        <title>Detail</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>   
      <div>
          {/* {console.log(props)} */}
          <nav className="navbar navbar-expand-lg navbar-light bg-primary ">
        <div className="container-fluid ">
            <a className="navbar-brand text-light mx-5" href="/">BLOG.Me</a>
         
            <button className="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span className="navbar-toggler-icon"></span>
            </button>
            <div className="collapse navbar-collapse" id="navbarNav">
            <ul className="navbar-nav">
                <li className="nav-item">

                <Link href="/">
                    <a className="nav-link  mx-3">Home</a>
                </Link>
                
                </li>
                <li className="nav-item">
                <Link href="/post">
                    <a className="nav-link mx-3 active" >Post</a>
                </Link>
                </li>
                <li className="nav-item">
                <Link href="/author">
                    <a className="nav-link mx-3" >Author</a>
                </Link>
                </li>
            
            </ul>
            </div>
        </div>
        </nav>
        </div>



      <main className={styles.main2}>
        <div className={styles.grid2}>
            
                <Card className="bg-dark text-white text-left">
                    <Card.Header className='display-1'>{posts.title.rendered}</Card.Header>
                    <Card.Body>
                        {/* <Card.Title>title</Card.Title> */}
                        <Card.Text dangerouslySetInnerHTML={{__html: posts.content.rendered}} />
                       
                        {/* <Button variant="primary">Go somewhere</Button> */}
                    </Card.Body>
                    <Card.Footer className="text-muted">2 days ago</Card.Footer>
                </Card>
                <InputGroup className="mt-4 w-100  px-5">
                    <FormControl
                    placeholder="Comment Here!!"
                    aria-label="Recipient's username"
                    aria-describedby="basic-addon2"
                    value={content}
                    onChange={handleChange}
                    />
                    <Button onClick={()=> checkpost()} variant="outline-secondary" id="button-addon2">
                    Send
                    </Button>
                </InputGroup>

                <div>
                </div>

                {commented.map(item => (
                    <Card className="mt-4 w-75">

                    <Card.Header>{item.author_name}
                    
    
                    </Card.Header>
                    <Card.Body>
                        
                        <Card.Text dangerouslySetInnerHTML={{__html: item.content.rendered}} />
                       
                    </Card.Body>
                </Card>
                    ))}
                
                

        </div>
      </main>
      
     
   
      

    </div>
  )
}

export const getServerSideProps = async (context) => {
    // Fetch data from external API
    const res = await fetch(`https://fswd-wp.devnss.com/wp-json/wp/v2/posts/` + context.query.postid)
    const data = await res.json()
  
  
    // Pass data to the page via props
    // console.log(context)
    return { 
        props:
            { 
                id: context.query.postid,
                posts : data,
            }}    
  }

  

