import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import 'bootstrap/dist/css/bootstrap.min.css';
import Link from 'next/link'
import {Card, Button, Modal }from 'react-bootstrap';
   
import { useEffect, useState } from "react"
import Parser from 'html-react-parser'



export default function Posts({ data ,data2 }) {
    const [posts, setPosts] = useState(data)
    const [showposts, setShowPosts] = useState(data)
  
    const [categories, setCategories] = useState(data2)
    const [isactiveModel, setIsactiveModel] = useState(true)
    const [idpostNow, setIdPostNow] = useState()





    function readMore(post) {
        
       
        // setIdPostNow(id)
        // console.log(post)
       
    }

    function selectAll() {
        setShowPosts(data)

    }

    function selectCategory(id) {
            // console.log(id)
            // setPosts(data)
            // console.log(posts)
            const ans = posts.filter(post => {
                        // console.log(post.categories),
                        return post.categories.includes(id)
                        // console.log(post.categories.includes(id))
                        }
                    ) 
            setShowPosts(ans)
    //    console.log(posts)   
    }

  

   
    

  return (
    <div className={styles.container}>
        <div className='bg-dark'>
      <Head>
        <title>Aren</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>  


<div>
    <nav className="navbar navbar-expand-lg navbar-light bg-primary ">
        <div className="container-fluid ">
            <a className="navbar-brand text-light mx-5" href="/">BLOG.Me</a>
         
            <button className="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span className="navbar-toggler-icon"></span>
            </button>
            <div className="collapse navbar-collapse" id="navbarNav">
            <ul className="navbar-nav">
                <li className="nav-item">

                <Link href="/">
                    <a className="nav-link  mx-3">Home</a>
                </Link>
                
                </li>
                <li className="nav-item">
                <Link href="/post">
                    <a className="nav-link mx-3 active" >Post</a>
                </Link>
                </li>
                <li className="nav-item">
                <Link href="/author">
                    <a className="nav-link mx-3" >Author</a>
                </Link>
                </li>
            
            </ul>
            </div>
        </div>
        </nav>
</div>

        <Button onClick={() => selectAll()} key={0} style={{ marginLeft : '4rem', marginRight : '1rem'  }} variant="outline-primary">All</Button>
    {categories.map(category => (
        <Button onClick={() => selectCategory(category.id)} key={category.id} style={{ margin : '1rem' }} variant="outline-primary">{category.name}</Button>
    ))}
      <main className={styles.main}>
        <div className={styles.grid}>
        
        {showposts.map(post =>(
            // console.log(post),

            <Card key={post.id} style={{ width: '20rem', margin: '1.5rem'}}>
            {/* <Card.Img variant="top" src={author.avatar_urls[96]}/> */}
            <Card.Body>
                <Card.Title>{post.title.rendered}</Card.Title>
                {/* <Card.Text dangerouslySetInnerHTML={{__html: post.excerpt.rendered}}> */}
                 <Card.Text > 
                    <div dangerouslySetInnerHTML={{__html: post.excerpt.rendered}}>
                    </div>
                    
                </Card.Text>
              
                <Link as={'/postdetail'} href={{pathname :"/postdetail", query : { postid : post.id }}}>
                    <Button >Read More...</Button>
                </Link>
               
            </Card.Body>
            <Card.Footer className="text-muted">{post.modified}</Card.Footer>
            </Card>
        ))}
        </div>
      </main>
   
      

      

    </div>
    </div>
  )
}

export async function getServerSideProps() {
    // Fetch data from external API
    const res = await fetch(`https://fswd-wp.devnss.com/wp-json/wp/v2/posts`)
    const data = await res.json()

    const res2 = await fetch(`https://fswd-wp.devnss.com/wp-json/wp/v2/categories`)
    const data2 = await res2.json()
  
    // Pass data to the page via props
    return { props: { data , data2} }
  }

  

